# Disable some built-in rules
config:
  default: true

  # The same headline in different nested sections is okay (and necessary for
  # CHANGELOG.md).
  no-duplicate-header:
    allow_different_nesting: true

# Fix any fixable errors
fix: true
